name: ASCII Artwork workflow
on: push
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: list repo files
              run: ls -ltra

            - name: Execute shell script
              run: |
                chmod +x ascii_script.sh
                ./ascii_script.sh
            
            # - name: list files
            #   run: ls -a
            
            # - name: Read file
            #   run: cat README.md
