name: ASCII Artwork workflow
on: push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: list repo files
              run: ls -ltra
    test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: test phase
            # - name: Execute shell script
            #   run: |
            #     chmod +x ascii_script.sh
            #     ./ascii_script.sh
            
            # - name: list files
            #   run: ls -a
              run: cat README.md

    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: deploy stage
              run: echo "Deploy stage"
