name: ASCII Artwork workflow
on: push
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: install cowsay library
              run: sudo apt-get install cowsay -y
            
            - name: ASCII artwork
              run: cowsay -f dragon >> dragon.txt

            - name: read dragon.txt
              run: cat dragon.txt

            - name: list files
              run: |
                echo "my first github action"
                ls -ltra
                cat README.md
            # - name: list files
            #   run: ls -a
            
            # - name: Read file
            #   run: cat README.md
