name: my first workflow
on: push
jobs:
    firstjob:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6
              
            - name: Multiline Command Execution
              run: |
                echo "my first github action"
                ls -ltr
                cat README.md
            
            - name: Cowsay artwork
              run: cowsay -f dragon
            # - name: list files
            #   run: ls -a
            
            # - name: Read file
            #   run: cat README.md
